export const phoneLengthByCountry = {
  AE: { name: "United Arab Emirates", length: 9 },
  AG: { name: "Antigua and Barbuda", length: 10 },
  AL: { name: "Albania", length: 9 },
  AR: { name: "Argentina", length: 10 },
  AT: { name: "Austria", length: 10 },
  AU: { name: "Australia", length: 9 },
  BA: { name: "Bosnia and Herzegovina", length: 8 },
  BB: { name: "Barbados", length: 10 },
  BD: { name: "Bangladesh", length: 10 },
  BE: { name: "Belgium", length: 9 },
  BH: { name: "Bahrain", length: 8 },
  BO: { name: "Bolivia", length: 8 },
  BR: { name: "Brazil", length: 11 },
  BS: { name: "Bahamas", length: 10 },
  BG: { name: "Bulgaria", length: 9 },
  BY: { name: "Belarus", length: 9 },
  CA: { name: "Canada", length: 10 },
  KH: { name: "Cambodia", length: 9 },
  CM: { name: "Cameroon", length: 9 }, // optional
  CL: { name: "Chile", length: 9 },
  CN: { name: "China", length: 11 },
  CO: { name: "Colombia", length: 10 },
  CR: { name: "Costa Rica", length: 8 },
  HR: { name: "Croatia", length: 9 },
  CZ: { name: "Czech Republic", length: 9 },
  DK: { name: "Denmark", length: 8 },
  DM: { name: "Dominica", length: 10 },
  EC: { name: "Ecuador", length: 9 },
  EG: { name: "Egypt", length: 10 },
  ET: { name: "Ethiopia", length: 9 },
  FI: { name: "Finland", length: 9 },
  FJ: { name: "Fiji", length: 7 },
  FR: { name: "France", length: 9 },
  DE: { name: "Germany", length: 10 },
  GH: { name: "Ghana", length: 9 },
  GR: { name: "Greece", length: 10 },
  GD: { name: "Grenada", length: 10 },
  HK: { name: "Hong Kong", length: 8 },
  HU: { name: "Hungary", length: 9 },
  IS: { name: "Iceland", length: 7 }, // optional
  IN: { name: "India", length: 10 },
  ID: { name: "Indonesia", length: 10 },
  IR: { name: "Iran", length: 10 },
  IQ: { name: "Iraq", length: 10 },
  IE: { name: "Ireland", length: 9 },
  IL: { name: "Israel", length: 9 },
  IT: { name: "Italy", length: 10 },
  JM: { name: "Jamaica", length: 10 },
  JP: { name: "Japan", length: 10 },
  JO: { name: "Jordan", length: 9 },
  KZ: { name: "Kazakhstan", length: 10 },
  KE: { name: "Kenya", length: 9 },
  KR: { name: "South Korea", length: 10 },
  KW: { name: "Kuwait", length: 8 },
  KG: { name: "Kyrgyzstan", length: 9 },
  LA: { name: "Laos", length: 8 },
  LB: { name: "Lebanon", length: 8 },
  LC: { name: "Saint Lucia", length: 10 },
  LK: { name: "Sri Lanka", length: 9 },
  MY: { name: "Malaysia", length: 9 },
  MV: { name: "Maldives", length: 7 }, // optional
  MT: { name: "Malta", length: 8 }, // optional
  MX: { name: "Mexico", length: 10 },
  MD: { name: "Moldova", length: 8 }, // optional
  MN: { name: "Mongolia", length: 8 },
  MA: { name: "Morocco", length: 9 },
  MZ: { name: "Mozambique", length: 9 }, // optional
  MM: { name: "Myanmar", length: 9 },
  NP: { name: "Nepal", length: 10 },
  NL: { name: "Netherlands", length: 9 },
  NZ: { name: "New Zealand", length: 9 },
  NG: { name: "Nigeria", length: 10 },
  NO: { name: "Norway", length: 8 },
  OM: { name: "Oman", length: 8 },
  PK: { name: "Pakistan", length: 10 },
  PW: { name: "Palau", length: 7 }, // optional
  PA: { name: "Panama", length: 8 }, // optional
  PG: { name: "Papua New Guinea", length: 8 },
  PY: { name: "Paraguay", length: 9 },
  PE: { name: "Peru", length: 9 },
  PH: { name: "Philippines", length: 10 },
  PL: { name: "Poland", length: 9 },
  PT: { name: "Portugal", length: 9 },
  QA: { name: "Qatar", length: 8 },
  RO: { name: "Romania", length: 10 },
  RU: { name: "Russia", length: 10 },
  RW: { name: "Rwanda", length: 9 }, // optional
  LC: { name: "Saint Lucia", length: 10 },
  VC: { name: "Saint Vincent and the Grenadines", length: 10 },
  KN: { name: "Saint Kitts and Nevis", length: 10 },
  SA: { name: "Saudi Arabia", length: 9 },
  RS: { name: "Serbia", length: 9 },
  SG: { name: "Singapore", length: 8 },
  SK: { name: "Slovakia", length: 9 },
  SI: { name: "Slovenia", length: 8 },
  ZA: { name: "South Africa", length: 9 },
  ES: { name: "Spain", length: 9 },
  LK: { name: "Sri Lanka", length: 9 },
  SE: { name: "Sweden", length: 9 },
  CH: { name: "Switzerland", length: 9 },
  TW: { name: "Taiwan", length: 9 },
  TJ: { name: "Tajikistan", length: 9 },
  TZ: { name: "Tanzania", length: 9 },
  TH: { name: "Thailand", length: 9 },
  TL: { name: "Timor-Leste", length: 8 }, // optional
  TT: { name: "Trinidad and Tobago", length: 10 },
  TN: { name: "Tunisia", length: 8 },
  TR: { name: "Turkey", length: 10 },
  TM: { name: "Turkmenistan", length: 8 },
  UG: { name: "Uganda", length: 9 },
  UA: { name: "Ukraine", length: 9 },
  GB: { name: "United Kingdom", length: 10 },
  US: { name: "United States", length: 10 },
  UY: { name: "Uruguay", length: 9 },
  UZ: { name: "Uzbekistan", length: 9 },
  VE: { name: "Venezuela", length: 10 },
  VN: { name: "Vietnam", length: 9 },
  ZM: { name: "Zambia", length: 9 },
  ZW: { name: "Zimbabwe", length: 9 },

  // Default
  DEFAULT: { name: "Unknown", length: 10 },
};
